project_id = "opekwztldtrylagmupoo"

[functions.ai-assistant]
verify_jwt = false

[functions.list-users]
verify_jwt = false

[functions.assign-role]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.ga4-analytics]
verify_jwt = false


